const productsData = [
  {
    category: "soup",
    price: 10.0,
    strMeal: "Rosół (Polish Chicken Soup)",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/lx1kkj1593349302.jpg",
    idMeal: "53020",
    ingredients: [
      "Chicken Legs",
      "Onions",
      "Carrots",
      "Leek",
      "Celery",
      "Cabbage",
      "Cloves",
      "Allspice",
      "Bay Leaf",
      "Parsley",
      "Dill",
      "Pepper",
      "Salt",
    ],
  },
  {
    category: "soup",
    price: 8.0,
    strMeal: "French Onion Soup",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/xvrrux1511783685.jpg",
    idMeal: "52903",
    ingredients: [
      "Butter",
      "Olive Oil",
      "Onion",
      "Sugar",
      "Garlic Clove",
      "Plain Flour",
      "Dry White Wine",
      "Beef Stock",
      "Bread",
      "Gruyère",
    ],
  },
  {
    category: "soup",
    price: 7.5,
    strMeal: "Broccoli & Stilton soup",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
    idMeal: "52842",
    ingredients: [
      "Rapeseed Oil",
      "Onion",
      "Celery",
      "Leek",
      "Potatoes",
      "Butter",
      "Vegetable Stock",
      "Broccoli",
      "Stilton Cheese",
    ],
  },
  {
    category: "soup",
    price: 7.0,
    strMeal: "Creamy Tomato Soup",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/stpuws1511191310.jpg",
    idMeal: "52841",
    ingredients: [
      "Olive Oil",
      "Onions",
      "Celery",
      "Carrots",
      "Potatoes",
      "Bay Leaf",
      "Tomato Puree",
      "Sugar",
      "White Vinegar",
      "Chopped Tomatoes",
      "Passata",
      "Vegetable Stock Cube",
      "Whole Milk",
    ],
  },
  {
    category: "soup",
    price: 7.0,
    strMeal: "Lentil Soup",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/58oia61564916529.jpg",
    idMeal: "52977",
    ingredients: [
      "Lentils",
      "Onion",
      "Carrots",
      "Tomato Puree",
      "Cumin",
      "Paprika",
      "Mint",
      "Thyme",
      "Black Pepper",
      "Red Pepper Flakes",
      "Vegetable Stock",
      "Water",
      "Sea Salt",
    ],
  },
  {
    category: "soup",
    price: 10.0,
    strMeal: "Mushroom soup with buckwheat",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/1ngcbf1628770793.jpg",
    idMeal: "53059",
    ingredients: [
      "Mushrooms",
      "Buckwheat",
      "Vegetable Oil",
      "Onion",
      "Garlic",
      "Bay Leaf",
      "Vegetable Stock Cube",
      "Sour Cream",
      "White Wine Vinegar",
      "Parsley",
    ],
  },

  {
    category: "salad",
    price: 15.5,
    strMeal: "Beef Banh Mi Bowls with Sriracha",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/z0ageb1583189517.jpg",
    idMeal: "52997",
    ingredients: [
      "Rice",
      "Onion",
      "Lime",
      "Garlic Clove",
      "Cucumber",
      "Carrots",
      "Ground Beef",
      "Soy Sauce",
    ],
  },
  {
    category: "salad",
    price: 14.0,
    strMeal: "Corned Beef and Cabbage",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/xb97a81583266727.jpg",
    idMeal: "52998",
    ingredients: ["Beef Brisket", "Small Potatoes", "Carrots", "Cabbage"],
  },
  {
    category: "salad",
    price: 16.0,
    strMeal: "Chicken Quinoa Greek Salad",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg",
    idMeal: "53011",
    ingredients: [
      "Quinoa",
      "Butter",
      "Red Chilli",
      "Garlic",
      "Chicken Breast",
      "Olive Oil",
      "Black Olives",
      "Red Onions",
      "Feta",
      "Mint",
      "Lemon",
    ],
  },
  {
    category: "salad",
    price: 12.5,
    strMeal: "Kung Pao Chicken",
    imgMeal: "https://www.themealdb.com/images/media/meals/1525872624.jpg",
    idMeal: "52945",
    ingredients: [
      "Sake",
      "Soy Sauce",
      "Sesame Seed Oil",
      "Corn Flour",
      "Water",
      "Chicken",
      "Chilli Powder",
      "Rice Vinegar",
      "Brown Sugar",
      "Spring Onions",
      "Garlic Clove",
      "Water Chestnut",
      "Peanuts",
    ],
  },

  {
    category: "appetizer",
    price: 16.0,
    strMeal: "Pierogi (Polish Dumplings)",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/45xxr21593348847.jpg",
    idMeal: "53019",
    ingredients: [
      "Butter",
      "Chopped Onion",
      "Sauerkraut",
      "Butter",
      "Chopped Onion",
      "Potatoes",
      "Eggs",
      "Sour Cream",
      "Flour",
      "Salt",
      "Baking Powder",
    ],
  },
  {
    category: "appetizer",
    price: 15.5,
    strMeal: "Gołąbki (cabbage roll)",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/q8sp3j1593349686.jpg",
    idMeal: "53021",
    ingredients: [
      "Cabbage",
      "Butter",
      "Onion",
      "Ground Beef",
      "Ground Pork",
      "Rice",
      "Garlic",
      "Salt",
      "Black Pepper",
      "Tomato Puree",
    ],
  },
  {
    category: "appetizer",
    price: 13.0,
    strMeal: "Bitterballen (Dutch meatballs)",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg",
    idMeal: "52979",
    ingredients: [
      "Butter",
      "Flour",
      "Beef Stock",
      "Onion",
      "Parsley",
      "Beef",
      "Salt",
      "Pepper",
      "Nutmeg",
      "Flour",
      "Eggs",
      "Breadcrumbs",
    ],
  },
  {
    category: "appetizer",
    price: 15.5,
    strMeal: "Cevapi Sausages",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/vc08jn1628769553.jpg",
    idMeal: "53055",
    ingredients: [
      "Minced Beef",
      "Minced Pork",
      "Onion",
      "Garlic",
      "Parsley",
      "Paprika",
      "Baking Powder",
      "Breadcrumbs",
      "Water",
      "Vegetable Stock Cube",
      "Salt",
      "Pepper",
    ],
  },
  {
    category: "appetizer",
    price: 14.5,
    strMeal: "Boulangère Potatoes",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/qywups1511796761.jpg",
    idMeal: "52914",
    ingredients: [
      "Onions",
      "Thyme",
      "Olive Oil",
      "Potatoes",
      "Vegetable Stock",
    ],
  },
  {
    category: "appetizer",
    price: 13.0,
    strMeal: "Kumpir",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg",
    idMeal: "52978",
    ingredients: [
      "Potatoes",
      "Butter",
      "Cheese",
      "Onion",
      "Red Pepper",
      "Red Chile Flakes",
    ],
  },
  {
    category: "appetizer",
    price: 11.0,
    strMeal: "Crispy Eggplant",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/c7lzrl1683208757.jpg",
    idMeal: "53072",
    ingredients: [
      "Egg Plants",
      "Breadcrumbs",
      "Sesame Seed",
      "Eggs",
      "Salt",
      "Pepper",
      "Vegetable Oil",
    ],
  },
  {
    category: "appetizer",
    price: 14.5,
    strMeal: "Kentucky Fried Chicken",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/xqusqy1487348868.jpg",
    idMeal: "52813",
    ingredients: [
      "Chicken",
      "Oil",
      "Egg White",
      "Flour",
      "Brown Sugar",
      "Salt",
      "paprika",
      "onion salt",
      "chili powder",
      "black pepper",
      "celery salt",
      "sage",
      "garlic powder",
      "allspice",
      "oregano",
      "basil",
      "marjoram",
    ],
  },

  {
    category: "dish",
    price: 22.5,
    strMeal: "Beef Asado",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
    idMeal: "53071",
    ingredients: [
      "Beef",
      "Beef Stock Concentrate",
      "Tomato Puree",
      "Water",
      "Soy Sauce",
      "White Wine Vinegar",
      "Pepper",
      "Bay Leaf",
      "Lemon",
      "Tomato Sauce",
      "Butter",
      "Olive Oil",
      "Onion",
      "Garlic",
    ],
  },
  {
    category: "dish",
    price: 22.0,
    strMeal: "Beef Bourguignon",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg",
    idMeal: "52904",
    ingredients: [
      "Goose Fat",
      "Beef Shin",
      "Bacon",
      "Challots",
      "Chestnut Mushroom",
      "Garlic Clove",
      "Bouquet Garni",
      "Tomato Puree",
      "Red Wine",
      "Celeriac",
      "Olive Oil",
      "Thyme",
      "Rosemary",
      "Bay Leaf",
      "Cardamom",
    ],
  },
  {
    category: "dish",
    price: 23.4,
    strMeal: "Beef Brisket Pot Roast",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg",
    idMeal: "52812",
    ingredients: [
      "Beef Brisket",
      "Salt",
      "Onion",
      "Garlic",
      "Thyme",
      "Rosemary",
      "Bay Leaves",
      "beef stock",
      "Carrots",
      "Mustard",
      "Potatoes",
    ],
  },
  {
    category: "dish",
    price: 17.5,
    strMeal: "Beef Lo Mein",
    imgMeal: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    idMeal: "52952",
    ingredients: [
      "Beef",
      "Salt",
      "Pepper",
      "Sesame Seed Oil",
      "Egg",
      "Starch",
      "Oil",
      "Noodles",
      "Onion",
      "Minced Garlic",
      "Ginger",
      "Bean Sprouts",
      "Mushrooms",
      "Water",
      "Oyster Sauce",
      "Sugar",
      "Soy Sauce",
    ],
  },
  {
    category: "dish",
    price: 16.0,
    strMeal: "Beef stroganoff",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    idMeal: "52834",
    ingredients: [
      "Olive Oil",
      "Onions",
      "Garlic",
      "Butter",
      "Mushrooms",
      "Beef Fillet",
      "Plain Flour",
      "Creme Fraiche",
      "English Mustard",
      "Beef Stock",
      "Parsley",
    ],
  },
  {
    category: "dish",
    price: 24.0,
    strMeal: "Steak Diane",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/vussxq1511882648.jpg",
    idMeal: "52935",
    ingredients: [
      "Canola Oil",
      "Beef Fillet",
      "Beef Stock",
      "Butter",
      "Garlic",
      "Challots",
      "Mushrooms",
      "Brandy",
      "Heavy Cream",
      "Dijon Mustard",
      "Worcestershire Sauce",
      "Tabasco Sauce",
      "Parsley",
      "Chives",
      "Salt",
      "Pepper",
    ],
  },
  {
    category: "dish",
    price: 22.5,
    strMeal: "Szechuan Beef",
    imgMeal: "https://www.themealdb.com/images/media/meals/1529443236.jpg",
    idMeal: "52950",
    ingredients: [
      "Beef",
      "Salt",
      "Sesame Seed Oil",
      "Pepper",
      "Egg White",
      "Starch",
      "Oil",
      "Ginger",
      "Garlic",
      "Onion",
      "Carrots",
      "Green Pepper",
      "Celery",
      "Mushrooms",
      "Cooking wine",
      "Water",
      "Oyster Sauce",
      "Hotsauce",
      "Sugar",
      "Soy Sauce",
    ],
  },
  {
    category: "dish",
    price: 17.0,
    strMeal: "Chicken Couscous",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg",
    idMeal: "52850",
    ingredients: [
      "Olive Oil",
      "Onion",
      "Chicken Breast",
      "Ginger",
      "Harissa Spice",
      "Dried Apricots",
      "Chickpeas",
      "Couscous",
      "Chicken Stock",
      "Coriander",
    ],
  },
  {
    category: "dish",
    price: 20.0,
    strMeal: "General Tso's Chicken",
    imgMeal: "https://www.themealdb.com/images/media/meals/1529444113.jpg",
    idMeal: "52951",
    ingredients: [
      "Chicken Breast",
      "Plain Flour",
      "Egg",
      "Starch",
      "Baking Powder",
      "Salt",
      "Onion Salt",
      "Garlic Powder",
      "Water",
      "Chicken Stock",
      "Duck Sauce",
      "Soy Sauce",
      "Honey",
      "Rice Vinegar",
      "Sesame Seed Oil",
      "Gochujang",
      "Starch",
      "Garlic",
      "Spring Onions",
      "Ginger",
    ],
  },
  {
    category: "dish",
    price: 22.5,
    strMeal: "Jerk chicken with rice & peas",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/tytyxu1515363282.jpg",
    idMeal: "52937",
    ingredients: [
      "Chicken Thighs",
      "Lime",
      "Spring Onions",
      "Ginger",
      "Garlic",
      "Onion",
      "Red Chilli",
      "Thyme",
      "Lime",
      "Soy Sauce",
      "Vegetable Oil",
      "Brown Sugar",
      "Allspice",
      "Basmati Rice",
      "Coconut Milk",
      "Spring Onions",
      "Thyme",
      "Garlic",
      "Allspice",
      "Kidney Beans",
    ],
  },
  {
    category: "dish",
    price: 18.0,
    strMeal: "Potato Gratin with Chicken",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
    idMeal: "52780",
    ingredients: [
      "Potatoes",
      "Onions",
      "Olive Oil",
      "Chicken Stock",
      "Creme Fraiche",
      "Parmesan",
      "Chicken Breasts",
      "Bacon",
      "Spinach",
      "Peas",
    ],
  },
  {
    category: "dish",
    price: 19.0,
    strMeal: "Piri-piri chicken and slaw",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg",
    idMeal: "53039",
    ingredients: [
      "Chicken",
      "Red Chilli",
      "Garlic",
      "Ginger",
      "Dried Oregano",
      "Coriander",
      "Paprika",
      "Red Wine Vinegar",
      "Oil",
      "Red Onions",
      "Carrots",
      "Beetroot",
      "Cabbage",
      "Mayonnaise",
      "Greek Yogurt",
      "Red Wine Vinegar",
      "Cumin Seeds",
    ],
  },

  {
    category: "burger",
    price: 18.0,
    strMeal: "Big Mac",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
    idMeal: "53013",
    ingredients: [
      "Minced Beef",
      "Olive Oil",
      "Sesame Seed Burger Buns",
      "Onion",
      "Iceberg Lettuce",
      "Cheese",
      "Dill Pickles",
      "Mayonnaise",
      "White Wine Vinegar",
      "Pepper",
      "Mustard",
      "Onion Salt",
      "Garlic Powder",
      "Paprika",
    ],
  },
  {
    category: "burger",
    price: 17.0,
    strMeal: "Portuguese prego with greens",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/ewcikl1614348364.jpg",
    idMeal: "53042",
    ingredients: [
      "Beef Fillet",
      "Olive Oil",
      "Ciabatta",
      "Rocket",
      "Basil Leaves",
      "Parsley",
      "Jalapeno",
      "Vinegar",
      "Spring Onions",
      "Garlic",
      "Caster Sugar",
    ],
  },
  {
    category: "sandwich",
    price: 14.0,
    strMeal: "Chick-Fil-A Sandwich",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg",
    idMeal: "53016",
    ingredients: [
      "Chicken Breast",
      "Pickle Juice",
      "Egg",
      "Milk",
      "Flour",
      "Icing Sugar",
      "Paprika",
      "Salt",
      "Black Pepper",
      "Garlic Powder",
      "Celery Salt",
      "Cayenne Pepper",
      "Olive Oil",
      "Sesame Seed Burger Buns",
    ],
  },
  {
    category: "sandwich",
    price: 16.0,
    strMeal: "Chivito uruguayo",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg",
    idMeal: "53063",
    ingredients: [
      "Beef Brisket",
      "Bread",
      "Lettuce",
      "Tomato",
      "Ham",
      "Mozzarella",
      "Bacon",
      "Egg",
      "Onion",
      "Pepper",
    ],
  },
  {
    category: "sandwich",
    price: 15.0,
    strMeal: "Montreal Smoked Meat",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg",
    idMeal: "52927",
    ingredients: [
      "Beef Brisket",
      "Salt",
      "Black Pepper",
      "Coriander",
      "Sugar",
      "Bay Leaf",
      "Cloves",
      "Paprika",
      "Garlic",
      "Onion",
      "Dill",
      "English Mustard",
      "Celery Salt",
      "Red Pepper Flakes",
    ],
  },

  {
    category: "pie",
    price: 20.8,
    strMeal: "Beef and Mustard Pie",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
    idMeal: "52874",
    ingredients: [
      "Beef",
      "Plain Flour",
      "Rapeseed Oil",
      "Red Wine",
      "Beef Stock",
      "Onion",
      "Carrots",
      "Thyme",
      "Mustard",
      "Egg Yolks",
      "Puff Pastry",
      "Green Beans",
      "Butter",
      "Salt",
      "Pepper",
    ],
  },
  {
    category: "pie",
    price: 21.5,
    strMeal: "Beef and Oyster pie",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
    idMeal: "52878",
    ingredients: [
      "Beef",
      "Olive Oil",
      "Shallots",
      "Garlic",
      "Bacon",
      "Thyme",
      "Bay Leaf",
      "Stout",
      "Beef Stock",
      "Corn Flour",
      "Oysters",
      "Plain Flour",
      "Salt",
      "Butter",
      "Eggs",
    ],
  },
  {
    category: "pie",
    price: 20.8,
    strMeal: "Minced Beef Pie",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/xwutvy1511555540.jpg",
    idMeal: "52876",
    ingredients: [
      "Vegetable Oil",
      "Minced Beef",
      "Onion",
      "Tomato Puree",
      "Plain Flour",
      "Mushrooms",
      "Beef Stock",
      "Worcestershire Sauce",
      "Shortcrust Pastry",
      "Egg Yolks",
    ],
  },
  {
    category: "pie",
    price: 17.5,
    strMeal: "Vegetable Shepherd's Pie",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/w8umt11583268117.jpg",
    idMeal: "53000",
    ingredients: [
      "Potatoes",
      "Small Potatoes",
      "Salted Butter",
      "Mushrooms",
      "Brown Lentils",
      "Garlic",
      "Kosher Salt",
      "Onion",
      "Tomato Puree",
      "Bay Leaves",
      "Olive Oil",
      "Dry White Wine",
      "Vegetable Stock",
      "Cornstarch",
      "Soy Sauce",
      "Rosemary",
      "Parsley",
      "Sage",
      "Chives",
    ],
  },
  {
    category: "pie",
    price: 16.0,
    strMeal: "Burek",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
    idMeal: "53060",
    ingredients: [
      "Filo Pastry",
      "Minced Beef",
      "Onion",
      "Oil",
      "Salt",
      "Pepper",
    ],
  },
  {
    category: "pie",
    price: 17.0,
    strMeal: "Chicken Ham and Leek Pie",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/xrrtss1511555269.jpg",
    idMeal: "52875",
    ingredients: [
      "Chicken Stock",
      "Chicken Breast",
      "Butter",
      "Leek",
      "Garlic",
      "Plain Flour",
      "Milk",
      "White Wine",
      "Double Cream",
      "Ham",
      "Sea Salt",
      "Pepper",
      "Free-range Egg",
      "Beaten",
      "Cold Water",
    ],
  },

  {
    category: "patties",
    price: 13.0,
    strMeal: "Paszteciki (Polish Pasties)",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/c9a3l31593261890.jpg",
    idMeal: "53017",
    ingredients: [
      "Flour",
      "Egg",
      "Butter",
      "Onion",
      "Swede",
      "Beef Brisket",
      "Salt",
      "Pepper",
    ],
  },
  {
    category: "patties",
    price: 14.0,
    strMeal: "Beef Wellington",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
    idMeal: "52803",
    ingredients: [
      "Mushrooms",
      "English Mustard",
      "Olive Oil",
      "Beef Fillet",
      "Parma ham",
      "Puff Pastry",
      "Flour",
      "Egg Yolks",
    ],
  },
  {
    category: "patties",
    price: 12.5,
    strMeal: "Jamaican Beef Patties",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/wsqqsw1515364068.jpg",
    idMeal: "52938",
    ingredients: [
      "Plain Flour",
      "Salt",
      "Curry Powder",
      "Butter",
      "Minced Beef",
      "Allspice",
      "Black Pepper",
      "Vegetable Oil",
      "Onions",
      "Red Pepper",
      "Garlic",
      "Thyme",
      "Tomato Ketchup",
      "Water",
      "Egg",
    ],
  },

  {
    category: "dessert",
    price: 7.5,
    strMeal: "Rogaliki (Polish Croissant Cookies)",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/7mxnzz1593350801.jpg",
    idMeal: "53024",
    ingredients: [
      "Butter",
      "Egg Yolks",
      "Cream Cheese",
      "Baking Powder",
      "Flour",
      "Jam",
    ],
  },
  {
    category: "dessert",
    price: 7.5,
    strMeal: "Polskie Naleśniki (Polish Pancakes)",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/58bkyo1593350017.jpg",
    idMeal: "53022",
    ingredients: ["Flour", "Eggs", "Milk", "Water", "Salt", "Sugar", "Butter"],
  },
  {
    category: "dessert",
    price: 7.2,
    strMeal: "New York cheesecake",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/swttys1511385853.jpg",
    idMeal: "52858",
    ingredients: [
      "Butter",
      "Sour Cream",
      "Sugar",
      "Cream Cheese",
      "Caster Sugar",
      "Plain Flour",
      "Lemon Juice",
      "Eggs",
    ],
  },
  {
    category: "dessert",
    price: 5.5,
    strMeal: "Battenberg Cake",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/ywwrsp1511720277.jpg",
    idMeal: "52894",
    ingredients: [
      "Butter",
      "Caster Sugar",
      "Self-raising Flour",
      "Almonds",
      "Baking Powder",
      "Eggs",
      "Vanilla Extract",
      "Almond Extract",
      "Butter",
      "Pink Food Colouring",
      "Apricot",
      "Marzipan",
      "Icing Sugar",
    ],
  },
  {
    category: "dessert",
    price: 5.5,
    strMeal: "Carrot Cake",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/vrspxv1511722107.jpg",
    idMeal: "52897",
    ingredients: [
      "Vegetable Oil",
      "Plain Flour",
      "Bicarbonate Of Soda",
      "Sugar",
      "Eggs",
      "Salt",
      "Cinnamon",
      "Carrots",
      "Walnuts",
      "Cream Cheese",
      "Caster Sugar",
      "Butter",
    ],
  },
  {
    category: "dessert",
    price: 5.0,
    strMeal: "Summer Pudding",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/rsqwus1511640214.jpg",
    idMeal: "52889",
    ingredients: [
      "Strawberries",
      "Blackberries",
      "Redcurrants",
      "Raspberries",
      "Caster Sugar",
      "Bread",
    ],
  },
  {
    category: "dessert",
    price: 5.0,
    strMeal: "Sticky Toffee Pudding Ultimate",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/xrptpq1483909204.jpg",
    idMeal: "52793",
    ingredients: [
      "Medjool dates",
      "water",
      "vanilla extract",
      "self-raising flour",
      "bicarbonate of soda",
      "eggs",
      "butter",
      "demerara sugar",
      "black treacle",
      "milk",
      "ice cream",
      "muscovado sugar",
      "double cream",
    ],
  },
  {
    category: "dessert",
    price: 7.2,
    strMeal: "Chocolate Raspberry Brownies",
    imgMeal:
      "https://www.themealdb.com/images/media/meals/yypvst1511386427.jpg",
    idMeal: "52860",
    ingredients: [
      "Dark Chocolate",
      "Milk Chocolate",
      "Salted Butter",
      "Light Brown Soft Sugar",
      "Eggs",
      "Plain Flour",
      "Cocoa",
      "Raspberries",
    ],
  },
];

module.exports = productsData;
